[package]
name = "four-am"
version = "0.1.0"
authors = ["Kriston Costa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = "0.8.2"
image = "0.23.0-preview.0"
console_error_panic_hook = "0.1.6"

[dependencies.quicksilver]
git = "https://github.com/ryanisaacg/quicksilver"
branch = "master"

features = ["saving", "stdweb"]